redis:
    image: redis:4-alpine
    volumes:
        - "./tmp/redis:/data"
my:
    build: .
    ports:
        - 5000:5000
        - 5001:5001
        - 5555:5555
    volumes:
        - ".:/usr/src/app:ro"
    links:
        - redis
